version: '3.1'
services:
  web01:
    image: nginx:alpine
    ports:
      - 9090:80
  web02:
    image: adityaprabhakara/alpine_apache2
    environment:
      APACHE_PORT: 9999
    ports:
      - 9091:9999