apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog-wp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blog-wp
    spec:
      containers:
      - name: wp
        image: wordpress:php7.0
        ports:
        - name: blog-wp-port
          containerPort: 80
        env:
          - name: WORDPRESS_DB_USER
            value: root
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: blog-secrets
                key: db-password
          - name: WORDPRESS_DB_HOST
            value: 172.17.0.10
---
apiVersion: v1
kind: Service
metadata:
  name: blog-wp-svc
spec:
  ports:
  - port: 8888
    nodePort: 31005
    targetPort: blog-wp-port
    protocol: TCP
  selector:
    app: blog-wp
  type: NodePort            
