apiVersion: v1
kind: Service
metadata:
  name: blog-site-svc
spec:
  ports:
  - port: 8888
    nodePort: 31002
    targetPort: wp-full-port
    protocol: TCP
  selector:
    app: blog-site
  type: NodePort
